# -*- coding: utf-8 -*-
"""Análise de Dados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/138yej9ouZvz-lTn2iWBITC2qJBfyfBz7

#Montando uma Rotina para Análise de Dados

Projetos de Análise de dados são na verdade Desafios que as empresas precisam que você resolva.

##Desafio

### - Empresa Vende Bermudas
### - 5 Lojas
### - Está querendo aumentar vendas
### - Informações Disponíveis: Base de Vendas
"""

!pip install pandas
!pip install numpy

"""#Passo 01 Importar a Base de dados Para o python e Visualizar

> Bloco com recuo


"""

import pandas as pd
tabela = pd.read_excel('/content/drive/MyDrive/Caso Analise com Python 01/Vendas.xlsx')
display(tabela)

"""# Passo 2 - Pegar um panorama geral sobre a sua base de dados"""

faturamento_total = tabela["Valor Final"].sum()
faturamento_total

"""#Passo 3 - Começar sua análise Top Down"""

#faturamento por Loja
faturamento_por_loja = tabela[["ID Loja","Valor Final"]]
display(faturamento_por_loja)

faturamento_por_loja = tabela[["ID Loja","Valor Final"]].groupby("ID Loja").sum()
display(faturamento_por_loja)

faturamento_por_produto = tabela[["ID Loja","Produto","Valor Final"]].groupby(["ID Loja", "Produto"]).sum()
display(faturamento_por_produto)

faturamento_por_produto.drop(["Bourbon Shopping SP","Iguatemi Esplanada","Norte Shopping", "Center Shopping Uberlândia"], inplace=True)

display(faturamento_por_produto)